### ISSUE TITLE
make install should honor DESTDIR variable also for sysconfdir

### ISSUE THREAD

**Issue by cogano** [yuhu-/ebusd#26]
Hi,
running as unprivileged user:

    ./autogen.sh
    ./configure --prefix=/usr/local --sysconfdir=/etc
    make
    make DESTDIR=$HOME/tmp install

tries to install directly to /etc instead to $HOME/tmp/etc.

(Ubuntu 12.04.5 on armv7l)

**Comment by yuhu-** [comment]
Hi,
you could use ./autogen.sh --prefix=/usr/local --sysconfdir=/etc too.

**Comment by cogano** [comment]
@yuhu: thnx for the info, I wasn't aware about that one.
